#pragma once
#include <vector>
#include "typedefs.hpp"
using namespace std;


/* 
* Create all possible subsets of a set of `K` elements, also known as the powerset 
*/
MatrixXi create_powerset(int K);


/*
 * Create all possible partitions of a set
 * 
 * The total number of possible partitions is given by the
 * Bell number. Partitions are generated recursively: given
 * all possible partitions of a set of size `n`; the partitions
 * for a set of size `n + 1` are generated by inserting the additional
 * element (1) in all subsets for each previous partition; (2) as its
 * own subset for each previous partition.
 * 
 * @param collection : elements in the set, restricted to integers
 * @returns n1_partitions : a vector of possible partitions of the set. 
 * Each possible partition is represented by a vector, and within each partition
 * grouped subsets are also vectors. 
*/
vector<vector<vector<int>>> create_all_partitions(vector<int> collection);

