// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_mcmc_cpp
Rcpp::List run_mcmc_cpp(Rcpp::List args_data, Rcpp::List args_params, Rcpp::List args_MCMC, Rcpp::List args_progress, Rcpp::List args_functions);
RcppExport SEXP _Tapestry_run_mcmc_cpp(SEXP args_dataSEXP, SEXP args_paramsSEXP, SEXP args_MCMCSEXP, SEXP args_progressSEXP, SEXP args_functionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args_data(args_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_params(args_paramsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_MCMC(args_MCMCSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_progress(args_progressSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_functions(args_functionsSEXP);
    rcpp_result_gen = Rcpp::wrap(run_mcmc_cpp(args_data, args_params, args_MCMC, args_progress, args_functions));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Tapestry_run_mcmc_cpp", (DL_FUNC) &_Tapestry_run_mcmc_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_Tapestry(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
